### ISSUE TITLE
Support Bitcoin Cash

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#28]
Add support for certifications using BCH

**Comment by elliot-sawyer** [comment]
How do you configure the public and private keys for BCH?

**Comment by christopheradams** [comment]
@elliot-sawyer The config file does support BCH network, by updating your `config/local-development.yaml` with the following settings:

```yaml
app:
  defaultChain: bch
  defaultNetwork: testnet

chains:
  bch:
    networks:
      mainnet:
        incomingPrivateKey: xprvXXXXX
        outgoingPublicKey: xprvXXXXX
        feeMultiplier: 2
      testnet:
        incomingPrivateKey: tprvXXXXX
        outgoingPublicKey: tpubXXXXX
        feeMultiplier: 2

services:
  insight:
    bch:
      mainnet:
        url: https://bch-insight.bitpay.com
        api: /api
      testnet:
        url: https://test-bch-insight.bitpay.com
        api: /api
```

However, the Bitcoin Cash Insight servers from Bitpay may or may not be working, and we don't currently have any stable, public alternatives to them.
